#!/bin/bash

# get ostype
os="$OSTYPE"

if [[ "$os" =~ ^linux ]]; then
    path=~/.config/Code/User/snippets
    if [[ -d $path ]]; then
        cd $path
        code .
    else
        echo -e "\nSnippets directory not found...\n"
        read -p "Run sync-snippets script? (y/n) " ans
        if [[ "$ans" == "y" ]]; then
            sync-snippets
        fi
    fi
elif [[ "$os" =~ ^darwin ]]; then
    path=~/Library/Application\ Support/Code/User/snippets
    if [[ -d $path ]]; then
        cd "$path"
        code .
    else
        echo -e "\n Snippets directory not found...\n"
        read -p "Run sync-snippets script? (y/n) " ans
        if [[ "$ans" == "y" ]]; then
            sync-snippets
        fi
    fi
else
    echo "Not sure where to find the Snippets directory"
fi

