#!/bin/bash

# get ostype
os="$OSTYPE"

if [[ "$os" =~ ^linux ]]; then
    path=~/.config/Code/User/snippets
    if [[ -d $path ]]; then
        cd $path
        echo -e "\n - Pulling snippets from master branch\n"
        git pull origin master
    else
        echo -e "\n - No snippets directory found, creating one now at $path\n"
        mkdir $path
        cd $path
        git init
        echo -e "\n - Pulling snippets from master branch\n"
        git remote add origin git@github.com:imjackson/vscode-snippets.git
        git pull origin master
    fi
elif [[ "$os" =~ ^darwin ]]; then
    path=~/Library/'Application Support'/Code/User/snippets
    if [[ -d $path ]]; then
        cd $path
        echo -e "\n - Pulling snippets from master branch\n"
        git pull origin master
    else
        echo -e "\n - No snippets directory found, creating one now at $path\n"
        mkdir $path
        cd $path
        git init
        echo "\n - Pulling snippets from master branch\n"
        git remote add origin git@github.com:imjackson/vscode-snippets.git
        git pull origin master
    fi
else
    echo "Not sure where to find the Snippets directory"
fi

